name: CI Angular

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Rodar lint
        run: npm run lint

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build do projeto
        run: npm run build -- --configuration production

      # - name: Rodar testes
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless
